version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80" # Maps port 80 in the container to port 3000 on the host

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5000" # Maps port 5000 in the container to port 5000 on the host
    environment:
      - NODE_ENV=production
